### ISSUE TITLE
오류발생 해결문의

### ISSUE THREAD

**Issue by kimv100** [wikibook/flask#2]
안녕하세요. 공부하다 오류가 발생해 더 이상 진행을 할 수가 없어 문의드립니다.

이클립스에서 ch02 hello.py 실행 시 아래와 같은 오류가 나는데
웹서버를 추가로 설치해야 하나요?

조치방법을 구체적으로 부탁드립니다.

<오류내용>
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

**Comment by wikibook** [comment]
안녕하세요? 저자분께도 문의 사항을 전달해 드렸는데,
말씀하신 것처럼 나오는 것은 정상적인 상황이라고 합니다.

알려주신 내용은 127.0.0.1 주소에 5000번 포트로 현재 웹 서버가 
정상적으로 실행되고 있음을 의미합니다.

감사합니다.
