### ISSUE TITLE
minitwit 웹페이지 소스를 활용할려고 합니다.

### ISSUE THREAD

**Issue by tpdns90321** [wikibook/flask#3]
제목 그대로 minitwit의 웹페이지 소스를 활용할려고 합니다. 그래서 라이센스가 어떻게 되는지 궁금해서 질문드립니다.

**Comment by liks79** [comment]
안녕하세요.
minitwit은 Flask 공식 매뉴얼에 포함되어 있는 예제로 책에서 해당 코드를 인용한것입니다.
minitwit은 Flask와 동일한 라이선스인 BSD 라이선스로 배포되고 있습니다.

BSD는 MIT, Apache등과 더블어 대표적인 Permissive 라이선스로 강력한 Copyleft를 요구하는 GPL계열과는 달리
원본 라이선스 문구를 훼손 하지 않으신다면 (저작인격권) 사용하시는데 무리가 없습니다.

책의 2부에서 다루고 있는 Photolog의 라이선스는 MIT 라이선스입니다.
위에서 언급했던것 처럼 원본 라이선스 문구를 유지 하신다면 사용하시는데 무리가 없습니다.

감사합니다.

**Comment by tpdns90321** [comment]
감사합니다
